server:
  port: 4000

spring:
  application:
    name: users-core

  datasource:
    url: jdbc:mysql://localhost:3306/hectify?useSSL=true&createDatabaseIfNotExist=true
    username: root
    password: elbouchouki

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  messages:
    basename: messages.messages
